# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [77]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [80]:
A = np.arange(1, 16).reshape(3,5)

In [82]:
print(A.shape)
print(A.size)
print(A.dtype)
print(A.ndim)

(3, 5)
15
int64
2


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [85]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [87]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [89]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [91]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [94]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [98]:
np.min(B)

1

In [100]:
np.min(B, axis=1)

array([1, 4, 7])

In [102]:
np.min(B, axis=0)

array([1, 2, 3])

In [104]:
np.argmin(B)

0

In [106]:
np.argmin(B, axis=0)

array([0, 0, 0])

In [108]:
np.sum(B)

45

In [110]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [112]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [115]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [117]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [120]:
# Att ge färre axlar = Numpy förstår det som att du vill välja alla element längs axlarna som inte har specifierats 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [123]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [125]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [127]:
# Genom att anitngen använda np.nditer() eller flatten()

In [129]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [131]:
for element in A.flatten():
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [133]:
# Vilken man ska använda när beror på om man har en större eller mindre datauppsättningar. 
# Är arrayen inte så stor så hade flatten() passat bättre då det är en enkel lösning för att iterera alla element.
# Är det lite större och mer avancerat så passar np.nditer() bättre då den har bland annat bättre kontroll över iterartionen genom flera axlar. 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [215]:
a = np.arange(30) 
b = a.reshape((2, 3, -1))
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [138]:
# a = np.arrange(30) innebär att den skapar en dimension och genererar sekvens med 30 element från 0 till 29
# b = a.reshape((2, 3, -1)) innebär att den skapar 3 dimensioner från arrayen a.
# reshape((2, 3, -1)) = 2 är block, 3 är rader och -1 innebär att Numpy ska själv räkna ut sista dimensionen så att när vi multiplicerar de vi får 30
# sista dimensionen blir då 5. (2 * 3 * 5) blir 30 
# ALLTSÅ 2 block, varje block har 3 rader och varje rad har 5 element.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [144]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [147]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [149]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [175]:
def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Båda inmatade matriserna ska vara av typen numpy.ndarray")
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation måste vara antingen 'add' eller 'multiply'")
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matriserna måste ha samma storlek för addition")
        return matrix1 + matrix2
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("För att multiplikationen ska vara möjlig måste antalet kolumner i första matrisen vara detsamma som antalet rader i andra matrisen.")
        return np.dot(matrix1, matrix2)

In [183]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

add_result = add_mult_matrices(matrix1, matrix2, 'add')
mult_result = add_mult_matrices(matrix1, matrix2, 'multiply')

print("Addition:", add_result)
print("Multiplication", mult_result)

Addition: [[ 6  8]
 [10 12]]
Multiplication [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [197]:
# 10.1.1
x = np.array([4, 3])

# A)
dimension_x = x.shape[0]
print("A):", dimension_x)

# B)
result_b = 5 * x
print("B):", result_b)

# C)
result_c = 3 * x
print("C):", result_c)

# D)
result_d = 5 * x + 3 * x
print("D):", result_d)

# E)
result_e = 8 * x
print("E):", result_e)

# F)
result_f = 4 * x - x
print("F):", result_f)

# G)
x_transposed = x.reshape(-1, 1)
print("G):", x_transposed.shape)

# H) 
try: 
    result_h = x + x_transposed
    x_defined = True
except ValueError:
    x_defined = False
if x.shape != x_transposed.shape:
    x_defined = False
print("H):", x_defined)

# I)
norm_x = np.linalg.norm(x)
print("I):", norm_x)

A): 2
B): [20 15]
C): [12  9]
D): [32 24]
E): [32 24]
F): [12  9]
G): (2, 1)
H): False
I): 5.0


In [201]:
# 10.1.2
v = np.array([3, 7, 0, 11])

# A) 
result_a = v.shape[0]
print("A):", result_a)

# B)
result_b = 2 * v
print("B):", result_b)

# C)
result_c = 5 * v + 2 * v
print("C):", result_c)

# D)
result_d = 4 * v - 2 * v
print("D):", result_d)

# E)
result_e = v.reshape(-1, 1)
dimension_transposed_v = result_e.shape
print("E):", dimension_transposed_v)

# F)
norm_v = np.linalg.norm(v)
print("F):", norm_v)

A): 4
B): [ 6 14  0 22]
C): [21 49  0 77]
D): [ 6 14  0 22]
E): (4, 1)
F): 13.379088160259652


In [207]:
# 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# A)
norm_v1 = np.linalg.norm(v1)
print("A):", norm_v1)

# B)
norm_v1_minus_v2 = np.linalg.norm(v1 - v2)
print("B):", norm_v1_minus_v2)

A): 7.14142842854285
B): 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [225]:
# 10.2.1

A = np.array([[2, .1, 1],[1, -1, 1]])
B = np.array([[4, -2], [2, -4], [1, -2]])
C = np.array([[1, 2], [2, 1], [1, -2]])
D = np.array([[3, 4], [4, 3]])
E = np.array ([[1], [2]])
I = np.eye(2)

# A)
print("A):", 2 * A)

# B)
try:
    result_b = B - 2 * A
    print("B):", result_b)
except ValueError:
    print("B): B - 2A är inte definierat")

# C)
try:
    result_c = 3 * C - 2 * E
    print("C):", result_c)
except ValueError:
    print("C): 3C - 2E är inte definierat")

# D)
try:
    result_d = 2 * D - 3 * C
    print("D):", result_d)
except ValueError:
    print("D): 2D - 3C är inte definierat")

# E)
d_transposed = D.T
try:
    result_e = d_transposed + 2 * D
    print("E):", result_e)
except ValueError:
    print("E): D^T + 2D är inte definierat")

# F)
c_transposed = C.T
d_transposed = D.T
try:
    result_f = 2 * c_transposed - 2 * d_transposed
    print("F):", result_f)
except ValueError:
    print("F): 2C^T - 2D^T är inte definierat")

# G)
a_transposed = A.T
try:
    result_g = a_transposed - B
    print("A):", result_g)
except ValueError:
    print("G): A^T - B är inte definierat")


# H)
try: 
    result_h = np.dot(A, C)
    print("H):", result_h)
except ValueError:
    print("H): AC är inte definierat")

# I)
try:
    result_i = np.dot(C, D)
    print("I):", result_i)
except ValueError:
    print("I): CD är inte definierat")

# J)
try:
    result_j = np.dot(C, B)
    print("J):", result_j)
except ValueError:
    print("J): CB är inte definierat")

# K)
try:
    result_k = np.dot(C, I)
    print("K):", result_k)
except ValueError:
    print("K): CI är inte definierat")

# L)
b_transposed = B.T
try:
    result_l = np.dot(A, b_transposed)
    print("L):", result_l)
except ValueError:
    print("L): AB^T är inte definierat")


A): [[ 4.   0.2  2. ]
 [ 2.  -2.   2. ]]
B): B - 2A är inte definierat
C): 3C - 2E är inte definierat
D): 2D - 3C är inte definierat
E): [[ 9 12]
 [12  9]]
F): 2C^T - 2D^T är inte definierat
A): [[-2.   3. ]
 [-1.9  3. ]
 [ 0.   3. ]]
H): [[ 3.2  2.1]
 [ 0.  -1. ]]
I): [[11 10]
 [10 11]
 [-5 -2]]
J): CB är inte definierat
K): [[ 1.  2.]
 [ 2.  1.]
 [ 1. -2.]]
L): AB^T är inte definierat


In [213]:
# 10.2.2
A = np.array([[2, 3, 4], [5, 4, 1]])
a_transposed = A.T
result = np.dot(A, a_transposed)
print(result)

[[29 26]
 [26 42]]


In [217]:
# 10.2.3
A = np.array([[2, 1], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = np.dot(A, B)
AC = np.dot(A, C)

ab_equal_ac = np.array_equal(AB, AC)
b_not_equal_c = not np.array_equal(B, C)

print(AB)
print(AC)
print(ab_equal_ac)
print(b_not_equal_c)

[[ 5  5]
 [ 8 14]]
[[ 8  8]
 [ 8 14]]
False
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [16]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [18]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [22]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
# Jag kan kontrollera om det är en view eller copy genom attributet .base
# Om det är none så är det en copy, om det är en array så är det en view
# Ja, v1 kommer att ändras för att de delar samma data